version: '2'
services:
    fluxsdsi-app:
        image: fluxsdsi
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fluxsdsi-postgresql:5432/fluxSdsi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fluxsdsi-postgresql:
        extends:
            file: postgresql.yml
            service: fluxsdsi-postgresql
